version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: soap
    versions:
    - 0.36.0
  - dependency-name: lodash
    versions:
    - 4.17.20
